#! /bin/sh

ROOT=/newroot
CRYPTNAME=cryptroot
CRYPTDEV=/dev/nbd0
ROOTDEV=/dev/mapper/${CRYPTNAME}

cd $ROOT
#mkdir -p dev
#mkdir -p sys
#mkdir -p proc
#mount --bind /dev dev
#mount --bind /sys sys
#mount --bind /proc proc
#echo "Going to chroot to $ROOT..."
#chroot . /bin/bash << '__EOC__'

echo "Syncing kernel modules from scw..."
#export PATH=/sbin:/bin:/usr/sbin:/usr/bin
/oc-sync-kernel-modules
echo "Loading kernel modules ..."
depmod -a
modprobe dm-mod
modprobe dm-crypt
modprobe btrfs

echo "Starting mount real root device:"
cryptsetup open $CRYPTDEV $CRYPTNAME
partprobe $ROOTDEV
lsblk
mkdir -p /mnt
mount -o subvol=root $ROOTDEV /mnt
df
/bin/bash
echo "Now switching to real root"
sleep 2
exec switch_root /mnt /sbin/init "$@"
echo "SOMETHING IS WRONG !!! Should not be here !!!"
/bin/bash
